name = "DziwnyModPack"
author = "FFTV"
version = "1.0.27"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2891305509383c332e67c3ae33decafd75d46b8288d28033c445abac0f0e512"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
