name = "DziwnyModPack"
author = "FFTV"
version = "1.1.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7765db805b032f3b13db3c1ca53c7f08188e3c10eb574e83b42f22ff2593c5ff"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
